import { useState } from 'react'
import type { Placement, OverallPriority } from '../lib/supabase'
import { normalizeApplicationStatus, PRIORITY_LABELS, PRIORITY_COLORS, scoreBarColor, isTBC } from '../lib/utils'
import './PlacementCard.css'

interface Props { placement: Placement; isNew?: boolean; onUpdate?: (p: Placement) => void }

const APP_STATUS_OPTIONS = ['Not Applied', 'Saved', 'Applied', 'Assessment', 'Interview', 'Final Interview', 'Offer', 'Accepted', 'Rejected', 'Withdrawn']

function ScoreBar({ label, score }: { label: string; score: number | null }) {
  const val = score ?? 0
  return <div className="score-row"><span className="score-label">{label}</span><div className="score-bar-track"><div className="score-bar-fill" style={{ width: `${(val / 10) * 100}%`, background: scoreBarColor(val) }} /></div><span className="score-value">{score == null ? '—' : `${val}/10`}</span></div>
}

function DetailItem({ label, value }: { label: string; value: string | null }) {
  if (!value || isTBC(value)) return null
  return <div className="detail-item"><span className="detail-label">{label}</span><span className="detail-value">{value}</span></div>
}

export default function PlacementCard({ placement: p, isNew, onUpdate }: Props) {
  const [expanded, setExpanded] = useState(false)
  const priority = (p.overall_priority ?? 'LOW_PRIORITY') as OverallPriority
  const priorityColor = PRIORITY_COLORS[priority] ?? PRIORITY_COLORS.LOW_PRIORITY
  const priorityLabel = PRIORITY_LABELS[priority] ?? 'Low Priority'
  const status = normalizeApplicationStatus(p.application_status)
  const statusClass = status.replace(/\s+/g, '-').toLowerCase()
  const appStatus = p.app_status ?? 'Not Applied'
  const saveTracking = (changes: Partial<Placement>) => onUpdate?.({ ...p, ...changes })
  const handleAppStatusChange = (e: React.ChangeEvent<HTMLSelectElement>) => { const next = e.target.value; saveTracking({ app_status: next, date_applied: next === 'Applied' && !p.date_applied ? new Date().toISOString().slice(0, 10) : p.date_applied }) }

  return <article className={`placement-card priority-${priority.replace(/_/g, '-').toLowerCase()} ${isNew ? 'is-new' : ''} ${expanded ? 'is-expanded' : ''}`} onClick={() => setExpanded((e) => !e)}>
    <div className="pc-header"><div className="pc-titles"><h3 className="pc-company">{p.company}</h3><span className="pc-role">{p.specific_role ?? 'Role TBC'}</span></div><div className="pc-badges"><span className="priority-badge" style={{ background: priorityColor }}>{priorityLabel}</span><span className={`status-badge status-${statusClass}`}>{status}</span></div></div>
    <div className="pc-meta"><span className="meta-chip">{p.sector ?? '—'}</span><span className="meta-chip">{p.city ?? 'TBC'}, {p.country ?? 'TBC'}</span><span className="meta-chip">{p.placement_duration ?? 'TBC'}</span></div>
    <div className="pc-scores"><div className="cv-fit-display"><span className="cv-fit-number" style={{ color: scoreBarColor(p.cv_fit ?? 0) }}>{p.cv_fit ?? '—'}</span><span className="cv-fit-label">CV Fit /10</span></div><div className="mini-scores"><div className="mini-score"><span>Aero</span><b>{p.aerospace_relevance ?? '—'}</b></div><div className="mini-score"><span>Space</span><b>{p.rocket_space_relevance ?? '—'}</b></div><div className="mini-score"><span>F1</span><b>{p.f1_motorsport_relevance ?? '—'}</b></div><div className="mini-score"><span>CFD</span><b>{p.aero_cfd_relevance ?? '—'}</b></div><div className="mini-score"><span>Prop</span><b>{p.propulsion_relevance ?? '—'}</b></div><div className="mini-score"><span>Ctrl</span><b>{p.controls_avionics_relevance ?? '—'}</b></div></div></div>
    <div className="pc-key-info"><div className="key-info-row"><span className="ki-label">Opens</span><span className="ki-value">{p.exact_opening_date ?? 'TBC'}</span></div><div className="key-info-row"><span className="ki-label">Deadline</span><span className="ki-value">{p.exact_deadline ?? 'TBC'}</span></div><div className="key-info-row"><span className="ki-label">Salary</span><span className="ki-value">{p.salary ?? 'TBC'}</span></div></div>
    <div className={`pc-details ${expanded ? 'show' : ''}`}>
      <p className="pc-why"><strong>Why it fits:</strong> {p.why_it_fits ?? 'TBC'}</p><p className="pc-weaknesses"><strong>Concerns:</strong> {p.potential_weaknesses ?? 'TBC'}</p>
      <div className="pc-scores-grid"><ScoreBar label="Aerospace" score={p.aerospace_relevance} /><ScoreBar label="Rocket/Space" score={p.rocket_space_relevance} /><ScoreBar label="F1/Motorsport" score={p.f1_motorsport_relevance} /><ScoreBar label="Aero/CFD" score={p.aero_cfd_relevance} /><ScoreBar label="Propulsion" score={p.propulsion_relevance} /><ScoreBar label="Controls/Avionics" score={p.controls_avionics_relevance} /><ScoreBar label="Prestige" score={p.prestige} /><ScoreBar label="Career Value" score={p.career_value} /></div>
      <div className="pc-detail-section"><h4>Eligibility</h4><DetailItem label="Degree" value={p.degree_requirements} /><DetailItem label="Min Grade" value={p.min_grade_requirement} /><DetailItem label="Year of Study" value={p.year_of_study_requirement} /><DetailItem label="Skills" value={p.required_technical_skills} /><DetailItem label="Citizenship" value={p.citizenship_requirement} /><DetailItem label="Right to Work" value={p.right_to_work_requirement} /><DetailItem label="Security Clearance" value={p.security_clearance_requirement} /><DetailItem label="Visa" value={p.visa_requirement} /></div>
      <div className="pc-detail-section"><h4>Placement Details</h4><DetailItem label="Type" value={p.placement_type} /><DetailItem label="Duration" value={p.placement_duration} /><DetailItem label="Start" value={p.placement_start_date} /><DetailItem label="End" value={p.placement_end_date} /><DetailItem label="Department" value={p.department} /><DetailItem label="Benefits" value={p.other_benefits} /></div>
      <div className="pc-detail-section application-tracking-panel"><div className="tracking-heading"><div><h4>Application Tracking</h4><p>Keep your personal progress here. It is saved to the database.</p></div><span className={`app-stage-badge stage-${appStatus.toLowerCase().replace(/\s+/g, '-')}`}>{appStatus}</span></div><div className="tracking-grid"><label>Stage<select value={appStatus} onChange={handleAppStatusChange} onClick={(e) => e.stopPropagation()}>{APP_STATUS_OPTIONS.map((option) => <option key={option}>{option}</option>)}</select></label><label>Date applied<input type="date" value={p.date_applied ?? ''} onChange={(e) => saveTracking({ date_applied: e.target.value || null })} onClick={(e) => e.stopPropagation()} /></label><label>CV version<input value={p.cv_version ?? ''} placeholder="e.g. Aerospace CV v3" onChange={(e) => saveTracking({ cv_version: e.target.value || null })} onClick={(e) => e.stopPropagation()} /></label><label>Cover letter<select value={p.cover_letter_required ?? 'Unknown'} onChange={(e) => saveTracking({ cover_letter_required: e.target.value })} onClick={(e) => e.stopPropagation()}><option>Unknown</option><option>Yes</option><option>No</option><option>Not required</option></select></label><label>Referral / contact<input value={p.referral_contact ?? ''} placeholder="Name or contact" onChange={(e) => saveTracking({ referral_contact: e.target.value || null })} onClick={(e) => e.stopPropagation()} /></label><label>Interview date<input type="date" value={p.interview_date ?? ''} onChange={(e) => saveTracking({ interview_date: e.target.value || null })} onClick={(e) => e.stopPropagation()} /></label></div><label className="tracking-notes">Notes<textarea value={p.notes ?? ''} placeholder="Recruiter contact, interview feedback, next steps…" onChange={(e) => saveTracking({ notes: e.target.value || null })} onClick={(e) => e.stopPropagation()} /></label><div className="tracking-row"><label>Outcome</label><select value={p.outcome ?? ''} onChange={(e) => saveTracking({ outcome: e.target.value || null })} onClick={(e) => e.stopPropagation()}><option value="">No outcome yet</option><option>Accepted</option><option>Rejected</option><option>Withdrawn</option><option>Offer declined</option></select></div><DetailItem label="Verified" value={p.source_verified} /></div>
      <div className="pc-actions">{p.application_link && <a href={p.application_link} target="_blank" rel="noopener noreferrer" className="pc-apply-btn" onClick={(e) => e.stopPropagation()}>{status === 'Open Now' ? 'Apply Now' : status === 'Closed' ? 'View Careers' : 'View Application'}</a>}{p.careers_page && p.careers_page !== p.application_link && <a href={p.careers_page} target="_blank" rel="noopener noreferrer" className="pc-website-btn" onClick={(e) => e.stopPropagation()}>Careers Page</a>}{p.website && <a href={p.website} target="_blank" rel="noopener noreferrer" className="pc-website-btn" onClick={(e) => e.stopPropagation()}>Company Website</a>}</div>
    </div>
    <button className="pc-expand" onClick={(e) => { e.stopPropagation(); setExpanded((v) => !v) }}>{expanded ? 'Show less' : 'Track application / View details'}<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={`chevron ${expanded ? 'up' : ''}`}><polyline points="6 9 12 15 18 9" /></svg></button>
  </article>
}
