import { createClient } from '@supabase/supabase-js'

const rawSupabaseUrl = process.env.SUPABASE_URL?.trim().replace(/^['"]|['"]$/g, '')
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim().replace(/^['"]|['"]$/g, '')
if (!rawSupabaseUrl || !supabaseKey) { console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY GitHub Actions secrets.'); process.exit(1) }
let supabaseUrl
try { const parsed = new URL(rawSupabaseUrl); parsed.pathname=''; parsed.search=''; parsed.hash=''; supabaseUrl=parsed.toString().replace(/\/$/,'') } catch { console.error(`Invalid SUPABASE_URL secret: ${rawSupabaseUrl}`); process.exit(1) }
const supabase=createClient(supabaseUrl,supabaseKey,{auth:{persistSession:false,autoRefreshToken:false},realtime:{enabled:false}})
const today=new Date().toISOString().slice(0,10), timeoutMs=15000
function normaliseUrl(value){if(!value)return null;try{return new URL(value).toString()}catch{return null}}
function cleanText(value=''){return String(value).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim()}
async function checkUrl(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{let response;try{response=await fetch(url,{method:'HEAD',redirect:'follow',signal:controller.signal,headers:{'User-Agent':'placement-tracker-role-monitor/1.0'}})}catch{response=await fetch(url,{method:'GET',redirect:'follow',signal:controller.signal,headers:{'User-Agent':'placement-tracker-role-monitor/1.0'}})}return{ok:response.ok,status:response.status,finalUrl:response.url}}catch(error){return{ok:false,status:null,finalUrl:url,error:error?.message??'Unknown error'}}finally{clearTimeout(timer)}}
async function fetchPage(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{method:'GET',redirect:'follow',signal:controller.signal,headers:{'User-Agent':'placement-tracker-role-monitor/1.0',Accept:'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8'}});const html=await response.text();return{ok:response.ok,status:response.status,finalUrl:response.url,text:cleanText(html)}}catch(error){return{ok:false,status:null,finalUrl:url,text:'',error:error?.message??'Unknown error'}}finally{clearTimeout(timer)}}
function detectRoleStatus(pageText,roleTitle=''){const lower=String(pageText||'').replace(/\s+/g,' ').trim().toLowerCase(),title=String(roleTitle||'').trim().toLowerCase();const closedPatterns=[/(?:this|the)\s+(?:job|position|role|vacancy|opportunity)\s+(?:is|has been)\s+(?:closed|filled|removed|withdrawn)/i,/(?:job|position|role|vacancy|opportunity)\s+(?:is|has been)\s+(?:no longer available|closed|filled|withdrawn)/i,/applications?\s+(?:for|to)\s+(?:this|the)\s+(?:role|position|job|vacancy)\s+(?:is|are)\s+(?:closed|no longer being accepted)/i,/(?:applications?|apply)\s+(?:are|is)\s+(?:now\s+)?closed/i,/(?:application|apply)\s+deadline\s+(?:has\s+)?passed/i,/(?:we|the company)\s+(?:are|is)\s+no longer\s+(?:accepting|considering)\s+applications?/i];const openPatterns=[/(?:apply|submit|send)\s+(?:your\s+)?application/i,/apply\s+(?:now|today)/i,/(?:applications?|candidates?)\s+(?:are|is)\s+(?:still\s+)?(?:being\s+)?accepted/i,/(?:job|position|role|vacancy|opportunity)\s+(?:is|remains)\s+(?:open|available)/i,/(?:click|select)\s+(?:here|below)\s+to\s+apply/i,/(?:submit|complete)\s+(?:an?|your)\s+application/i];const closedMatch=closedPatterns.find(p=>p.test(lower));if(closedMatch)return{status:'Closed',confidence:'high',reason:closedMatch.source};const openMatch=openPatterns.find(p=>p.test(lower));if(openMatch)return{status:'Open Now',confidence:'high',reason:openMatch.source};if(title&&lower.includes(title)&&/application|candidate|vacancy|position|job details|job description/i.test(lower))return{status:'Unknown',confidence:'medium',reason:'Role page found but no definitive status signal.'};return{status:'Unknown',confidence:'low',reason:'No definitive status signal.'}}
async function main(){console.log(`Using Supabase project: ${new URL(supabaseUrl).hostname}`);const{data:placements,error}=await supabase.from('placements').select('id, company, specific_role, application_status, app_status, application_link, careers_page, source_url, source_verified');if(error)throw error;const active=(placements??[]).filter(p=>String(p.app_status??'').trim().toLowerCase()!=='not interested'),skipped=(placements?.length??0)-active.length;console.log(`Checking ${active.length} tracked opportunities... (${skipped} marked Not Interested skipped)`);let checked=0,broken=0,open=0,closed=0,unknown=0;for(const placement of active){const candidates=[placement.application_link,placement.careers_page,placement.source_url].map(normaliseUrl).filter(Boolean);if(!candidates.length)continue;let result=null,page=null,checkedUrl=null;for(const url of candidates){result=await checkUrl(url);checkedUrl=url;if(!result.ok)continue;page=await fetchPage(result.finalUrl||url);if(page.ok)break}checked++;const statusText=result?.ok?`URL reachable (${result.status})`:`URL check failed${result?.status?` (${result.status})`:''}`;const updates={source_date_checked:today,source_verified:`${statusText}; automatically checked ${today}`,updated_at:new Date().toISOString()};if(!result?.ok||!page?.ok){broken++;updates.notes=`Automated monitor: tracked URL could not be reached on ${today}. ${result?.error??''}`.trim();console.log(`${placement.company} — ${placement.specific_role??'role'}: ${statusText} (${checkedUrl})`)}else{const roleStatus=detectRoleStatus(page.text,placement.specific_role);if(roleStatus.status==='Open Now'){open++;updates.application_status='Open Now'}else if(roleStatus.status==='Closed'){closed++;updates.application_status='Closed'}else unknown++;updates.source_verified=`${statusText}; role status: ${roleStatus.status} (${roleStatus.confidence} confidence); automatically checked ${today}`;console.log(`${placement.company} — ${placement.specific_role??'role'}: ${roleStatus.status} (${roleStatus.confidence}) — ${checkedUrl}`)}const{error:updateError}=await supabase.from('placements').update(updates).eq('id',placement.id);if(updateError)console.error(`Failed updating ${placement.company} — ${placement.specific_role}:`,updateError.message)}console.log(`Monitor complete: ${checked} checked, ${open} open, ${closed} closed, ${unknown} unknown, ${broken} unreachable, ${skipped} Not Interested skipped.`)}main().catch(error=>{console.error(error);process.exit(1)})
